---
- name: "Creating inventory file to deploy Gitea"
  hosts: localhost
  connection: local

  vars_prompt:
    - name: "node_rpc"
      prompt: "Node RPC"
      private: no
      default: "tcp://node.alpha.obada.io:26657"

    - name: "faucet_mnemonic"
      prompt: "Faucet Mnemonic Phrase"
      private: no

    - name: "faucet_keyring_password"
      prompt: "Faucet Keyring Password"
      private: no

    - name: "faucet_domain"
      prompt: "Faucet Domain (Example: faucet.yournet.com)"
      private: no
      default: "faucet.obada.io"

    - name: "recaptcha_site_key"
      prompt: "Google Recaptcha Site Key"
      private: no

    - name: "acme_email"
      prompt: "Email Notifications About Domain Expiration"
      private: no
    
    - name: "ssh_host_ip"
      prompt: "SSH Host IP"
      private: no

    - name: "ssh_user"
      prompt: "SSH User"
      private: no
      default: root

    - name: "ssh_port"
      prompt: "SSH Port"
      private: no
      default: 22

    - name: "should_become"
      prompt: "Should Become Sudo or Not (say "no" if you provision from the root) from installation?"
      private: no

  tasks:
    - name: Generate inventory file
      template:
        src: "inventory.j2"
        dest: "/home/ansible/deployment/inventory"
        mode: 0600
